version: "3.1"
services:
    jenkins:
      container_name: jenkins
      image: jenkins/jenkins:latest
      volumes:
        - jenkins_home:/var/jenkins_home
      networks:
        - jenkins

    agent:
      container_name: jenkins-agent
      build: containers/ssh-agent
      volumes:
        - agent_home:/home/jenkins
        - /var/run/docker.sock:/var/run/docker.sock
      env_file:
        - .agent.env
      networks:
        - jenkins

    nginx:
      container_name: jenkins-proxy
      image: nginx:alpine
      volumes:
        - ./containers/nginx/jenkins.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 8085:80
      networks:
        - default
        - jenkins

networks:
  jenkins:

volumes:
  jenkins_home:
  agent_home:

