version: "3.1"
services:
    jenkins:
      container_name: jenkins
      image: jenkins/jenkins:lts-jdk11
      volumes:
        - jenkins_home:/var/jenkins_home
      ports:
        - 8080:8080

    agent:
      container_name: agent
      image: jenkins/ssh-agent
      env_file: 
        - agent.env
      volumes:
        - ./agent.pub:/home/jenkins/.ssh/authorized_keys
      ports:
        - 22:22
volumes:
  jenkins_home:

